In [ ]:
#1.ingestion script
#2.summary table or tables then optimize the query then basic cleaning and new columns create and save as table in database
#3.summary statistics distribution and boxplot then insights for outiers etc
#4.then on the basis of above insights clean properly one by one column.
#5.then start analysis insights and charts.

#use this file info for step 3 and 4

In [ ]:
#1.if one table then easy -- start with EDA and then cleaning

#2.if one very big table --- make dublicates --- then may be make fact and dimension tables or other way analysis

#3.if alot of big tables...
#then we have different ways to do analysis -- summary table or tables create 

#1. 1st way
#data modeling  --- fact tables and dimension tables
#like fact purchases -- fact sales --- fact vendor invoice
#dim vendor dim product dim store dim date dim po  ----- these will have primary keys and unique values no dublicates. 
#from fact to dimensions -- many to one relationship..


#2. 2nd way
#merge what you need relevant to questions at hand. means join left right etc..

#3. 3rd way
#build one denormalized analysis table. also join used left right..

#4. 4th way
#Aggregate directly per questions
#If you're just answering specific questions ("which vendor has highest freight," "which brand has best margin"), you don't need a 
#data model at all — just write the groupby/SQL query for that specific question straight against the raw tables




#we reduce big tables into one summary table and use it for reporting..

In [ ]:
# Data pre processing steps
# Problem
# data collection
# data integration/data pooling/consolidation/merging
#data cleaning (missing values, smoothing noisy data, outliers, inconsistency, duplicates)
#data transformation (scale, normalization, data aggregation[combine two or more variables], 
#data generalization[age column binning])
#data reduction(dimensionality reduction)  --  dimensionality reduction numerosity reduction data compression
#only keep important columns   #PCA analysis   #Multivariate analysis
#numerosity reduction  -- data encoding    -- male 1 female 0
#data discretization   --- numeric to categorical   binning clusters.

In [ ]:
#Descriptive statistics or EDA -- for understanding data
#summarize -- distribution -- data types -- correlation of features

#we do 4 things in Descriptive statistics EDA
#Composition - distribution - comparison - relationship

In [ ]:
import pandas as pd
df=pd.read_csv('Data/train.csv')   #bcz the data is in current working directory so simply give data then file name for path
df.head()

In [ ]:
#how big is the data?
df.shape


#how does the data look like?
#df.head()    #or
df.sample(5)   #it will return random 5


#are there any missing values?
df.isnull().sum()

#how does the data look mathematically
df.describe()

#are there any duplicated values?
df.duplicated().sum()

#how is the correlation between columns?   identify irrelevent columns.
#df.corr()['Survived']

import pandas as pd
import seaborn as sns

#understanding your data
#EDA using univariate analysis   -- single variable analysis -- understanding each column/variable.
#data types  --- numerical  and  categorical

# 1. Categorical Data   -- categorical columns analysis
# a. Countplot
sns.countplot(df['Embarked'])
#df['Survived'].value_counts().plot(kind='bar')


# b. PieChart
df['Sex'].value_counts().plot(kind='pie',autopct='%.2f')


# 2. Numerical Data    -- numerical columns analysis
# a. Histogram
import matplotlib.pyplot as plt
plt.hist(df['Age'],bins=5)


# b. Distplot      #improved version of histogram -- also tells skewness  -- line also created -- 
#                   # also called probability density estimation pdf  -- like 15% probability that age will be 40  -- y axis probability
sns.distplot(df['Age'])


# c. Boxplot
# points out of the min max points are outliers, the blue box is IQR q1(25th percentile) q2 q3(75th percentile), the line inside is median
# q1 to q3    >>> 50% data
# min >> q1-1.5*IQR        max>> q3+.1.5*IQR
sns.boxplot(df['Age'])



#understanding your data
#EDA using bivariate and multivariate analysis   -- analysis of 2 variables at a time
#cat - cat analysis
#num - num analysis (scatter plot)
#cat - num analysis

In [ ]:
##understanding your data
#EDA using bivariate and multivariate analysis   -- analysis of 2 variables at a time
#cat - cat analysis
#num - num analysis (scatter plot)
#cat - num analysis


#titanic = pd.read_csv('train.csv')      #buildin datasets inside sns
flights = sns.load_dataset('flights')
flights.head()


iris = sns.load_dataset('iris')
iris.head()

tips = sns.load_dataset('tips')    #buildin data sets inside sns
tips.head()

# 1. Scatterplot (Numerical - Numerical)
sns.scatterplot(data=tips,x='total_bill',y='tip',hue='sex',style='smoker',size='size')

# 2. Bar Plot (Numerical - Categorical)
import pandas as pd
titanic = pd.read_csv('Data/train.csv') 
titanic.head()


sns.barplot(data=titanic, x='Pclass', y='Age', hue='Sex')


import seaborn as sns
import matplotlib.pyplot as plt


# 3. Box Plot (Numerical - Categorical)
sns.boxplot(data=titanic, x='Sex', y='Age', hue='Survived')


# 4. Distplot (Numerical - Categorical)
sns.distplot(titanic[titanic['Survived']==0]['Age'],hist=False)
sns.distplot(titanic[titanic['Survived']==1]['Age'],hist=False)


# 5. HeatMap (Categorical - Categorical)
sns.heatmap(pd.crosstab(titanic['Pclass'],titanic['Survived']))


titanic.groupby('Embarked')['Survived'].mean() * 100

# 6. ClusterMap (Categorical - Categorical)
sns.clustermap(pd.crosstab(titanic['Parch'],titanic['Survived']))

# 7. Pairplot
sns.pairplot(iris,hue='species')

# 8. Lineplot (Numerical - Numerical)
flights.head()

new = flights.groupby('year')['passengers'].sum().reset_index()

sns.lineplot(data=new, x='year', y='passengers')


sns.clustermap(flights.pivot_table(values='passengers',index='month',columns='year'))



########################################################################################

In [ ]:
##extra   Some Basics
#len(my_list)      #my_list[2]      #my_list[-1]     #slicing  my_list[0:2]
#my_list[1:]       #my_list[:3]         #my_list[0:5:1] #it returns immediate next item can skip 1 same result
#my_list[0:5:2] #it returns by skiping 1 item -step given as 2 
#my_list[::2] same result as above 2 step one.
#my_list[6:1:-1] reverse slicing
#my_list[6:1:-2]
#fruits[2][1]  #at index 2 of main list then at index 1 of that within list --  list within list.

#fruits.append('orange')    #fruits.insert(0,'orange')   fruits[0]='plum'  fruits.extend(['melon','watermelon'])
#fruits.remove('orange')

#fruits2=fruits.copy()    #fruits.index('apple')

In [ ]:
#my_str=my_str.replace('c','7')    #my_str.upper()    #my_str.isnumeric()    #my_str.isalpha()
#'nitish        '.strip() #extra spcaes remove after nitish see the spaces.
#othermethods --- .startswith, .endswith, .digits, .isdigit, .swapcase

In [ ]:
# immutable ()   #only one item tuple   #my_tup2=('python',) # if only one item then must use ''''  , ''''
# comma at the end.

#grades3={"Hamza":{"english":80,"python":85},"abdullah":{"english":81,"python":79}}
#grades3["Hamza"]["english"]

In [ ]:
# check loops and functions python notebook also

In [ ]:
##pandas  #numpy
#df=pd.DataFrame({'population':[35,63,80,20],'GDP':[312,600,350,425],'surface area':[18373,18373,18363,19374],'HDI':[10,12,19,15],
#'continent':['abe','dez','ghi','jkl']},columns=['population','GDP','surface area','continent'])

#setting custom index       #df.index=['canada','france','germany','italy']

#fetch 1st 3rd 4th 6th rows     #a[[0,2,3,5]]    if 2d array/table

#and used foloowing to fetch columns
#a[:,[0,2,3]]  #the second part is columns whilw the 1st part means : all rows

#fetch 2nd and 3rd row and 2nd and 3rd column
#a2[1:,1:3]

In [ ]:
#df methods
#value_counts  #sort_values  #rank  #sort index  #set index   #rename index  #reset index
#unique #nunique #isnull #notnull #hasnans #dropna #drop_duplicates #drop
#apply #isin #corr #nlargest #nsmallest #insert #copy

#shape  #dtypes   #index   #columns   #values   #head and tail()   #sample()   
#info()   #describe()    #in sull()    #rename   #duplicated()

#groupby 

#merging #joining # concatenating 
#concat and append both do same thing but use always concat only.
#pd.concat([nov,dec],ignore_index=True)  #let nov data index 0 to 24 and dec 0 to 24 so ignore
#index means after nov 24 start from 25... dont start again from 0 for dec

#concat as multiindex df
#pd.concat([nov,dec],keys=['nov','dec'])
#we saying keep the index same 0 to 24 and 0 to 24
#but to differentiate add another index 'nov' for 1st df and 'dec' for second
#thats why called nultiindex df.
#it will concat up to down not side by side coulmn increase.
#it will be now 'nov'0   'nov'1 ......  'dec'0    'dec'1  .....

#extract info multiindex
#multi.loc['nov']     #it will extract only nov data.

#in nov extract 0 item
#multi.loc[('nov',0)]    #index1 name, index2 name

#concat hortizotally
#pd.concat([nov,dec], axis=1)


#merge  #like sql joins
#inner join   left join    right join    outer join

#alternate syntax for merge
#pd.merge
#leftTable.merge(RightTable,how='inner',on='student_id')

#pd.merge(leftTable,RightTable,how.....)
#
#

In [ ]:
###indexing 
#only rows retrieve   loc   iloc
#df.loc['canada']     #df.iloc[-1]     #print(df.iloc[[0,1,-1]])  #multiple rows/records retrieve

#column retrieve   -- no need to use loc iloc bcz thats index/related to records
#print(df[['population','GDP']])   #only columns retrieve

#print(df.loc['france':'italy',['population','GDP']])  #rows plus columns retrieve

#print(df.iloc[1:3],[0,3])   #1st one rows   2nd one columns. rows plus columns ret.

#print(df.iloc[1:3,1:3])   #rows and columns ret. by slicing

#students_data.rename(columns={'marks':'percent','package':'lpa'},inplace=True)
#students_data.sum(axis=0  #each column total sum

##select 1st 3rd and 4th rows     #movies.iloc[[0,4,5]]
#students.loc[['ali','iqra','waleed']]
#movies.iloc[0:3,0:3]   #first part row and 2nd part column
#movies.loc[0:2,'title_x':'poster_path']



##range(start,stop,step) --- used to generate sequence of numbers
#list(range(11))
#print(list(range(2,11,2)))

#for i in range(5):        #we can give list tuple string dic anything --all these are iterable
    #print(i)

In [ ]:
#numpy
#array   #matrices   #masked arrays
#arange---gives #s in a sequence
#random--from 0 to 1 random #s generates

#a=np.array([1,2,3])   #list pass

#1D --- vector
#2D --- matrix
#3D --- Tensor

#np.array([1,2,3],dtype=int)  #or float
#np.arange(1,11)   #or(11)
#np.arange(1,11,2)  #step 2 means skip 1 item and give next/2nd

#np.arange(1,11)   #1D array

#convert 1D to 2D
#np.arange(1,11).reshape(5,2)  #5*2=10 items total

#3D array
#np.arange(1,11).reshape(5,1,2)  #3D array  #product of reshape numbers should equal total items of the array. 5*1*2=10


#4D array
#np.arange(16).reshape(2,2,2,2)  #2*2*2*2=16

#if you want to initiate by random numbers
#between 0 and 1 numbers generate in shape 2D (3,4)
#np.random.random((3,4))

#np.linspace(-10,10,10)  #generate in range -10 to 10 equal distannce total 10 items last one 
# is # of items not steps

#a1=np.arange(10,dtype=np.int32).reshape(10,)  #1D as shape(10,)
#a2=np.arange(12,dtype=float).reshape(3,4)      #2D 
#a3=np.arange(8).reshape(2,2,2)                #3D

#a1=np.random.random((3,3))   #it generates random #s from 0 to 1. Shape 2D
#a1=np.round(a1*100)   #random #s from 0 to 1 multiped by 100

#or print(np.round(np.random.random((2,3))*100))


#indexing
#a1=np.arange(10)  #1D
#a2=np.arange(12).reshape(3,4)  #2D
#a3=np.arange(8).reshape(2,2,2)    #3D

#indexing 1D array--fetching items
#print(a1[-1])  #last item returns

#a2[rowindex#, columnindex#]
#print(a2[1,2])   #at row index# 1 and column index # 2 we have 6

#print(a3)  #3D shape(2,2,2)-- 1st position 2 indicates how many 2Ds
#so here 2 - 2D arrays of each shape (2,2) last 2 position 2s represnt shape of that 2 - 2D arrays
#as 3D is made up of 2Ds.. and 2D made up of 1Ds
#lets fetch 5
#a3[1st select which 2D of the 2-2Ds using index 0,1    ,  now select row index      ,  column index od that selected 2D]
#print(a3[1,0,1])

#2 or more arrays combine
#two ways  --- horizontally or vertically
#let 2 arrays with shape 2x2 and 2x2
#after stack 2x4  ---for horizontally stack--cols increased
#for vertical -4x2
#np.hstack(a4,a5)

#splitiing   --opposite of stacking
#np.hhsplit(a4,2)   #split a4 into 2 equal parts

#fetch 1st 3rd 4th 6th rows    if 2d 
#a[[0,2,3,5]]

#a=np.random.randint(1,100,24).reshape(6,4)
#np.concatenate((c,d),axis=0
#np.percentile(a,100) #will give the max numb
#a[np.isin(a,items)]    #search items elements in array a

#replace all values > 50 with 0
#np.where(a>50,0,a)

#print(np.sort(a,axis=0,kind=None,order=None))   #column wise sort

In [ ]:
##########################################################################################

In [ ]:
#Data preprocessing


#first drop duplicates then other things
#inconsistencies/Anomalies

#duplicates -- #first drop duplicates then other things
#inconsistent names(USA,united states) -- use replace
#handling mixed variables
#let in a column numeric and categorical mix  --- for exp. cabin. B5 C23 D41 --- split into 2 columns
#let column values -- 7 3 1 A C 4 D --- 2 columns create numeric and categorical --- 7 3 1 NA NA 4 NA and NA NA NA A C NA D

#inconsistent formats(date format)
#contradictory data(son age >father age)

In [ ]:
#pip install numpy pandas
#!pip install matplotlib

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Data/titanic.csv')
df.head()

  Cabin            Ticket number  Survived
0   NaN         A/5 21171      5         0
1   C85          PC 17599      3         1
2   NaN  STON/O2. 3101282      6         1
3  C123            113803      3         1
4   NaN            373450      A         0

In [ ]:
#lets clean the data one by one column..
#number column. first see unique values in number column. '5', '3', '6', 'A', '2', '1', '4'
#we can see one odd alphabet A 
#lets confirm first if its error or actual part of data using value count and bar plot
#confirmed that its actually part of data. bcz nubers and alphabets should be in sep columns so let create new column and sep them.

df['number'].unique()

fig = df['number'].value_counts().plot.bar()
fig.set_title('Passengers travelling with')

# columns create
# extract numerical part
df['number_numerical'] = pd.to_numeric(df["number"],errors='coerce',downcast='integer')
##dont directly change the original column.
#new column. number_numerical. converting the values of Orig. column to numeric values means data type change
#errors='coerce'... If a value cannot be converted to a number, Pandas replaces it with NaN (missing value) 
#instead of throwing an error.
#now whereever was A that will be 'nan' now in the new column. number_numerical.
#downcast='integer'.. Pandas tries to use the smallest integer data type that can hold the values to save memory.

# extract categorical part
df['number_categorical'] = np.where(df['number_numerical'].isnull(),df['number'],np.nan)
df.head()
#create another column where we will only bring the A and in rest of rows nan.
#np.where(condition, value_if_true, value_if_false) 
#where number_numerical column has null values then add what ever is in number column at that point
#if not null then add nan there.



#next lets fix cabin column.
df['Cabin'].unique()      #nan,         'C85',        'C123',         'E46',          'G6', 'C103',         'D56',          'A6', 'C23 C25 C27',

#Cabin column
#'C85',        'C123',         'E46',          'G6
#You can see starting from alphabet and ending with numbers.
#lets use reg expression to sep them.

#.str = "I want to perform string operations on every value in this panda column/Series."
#.extract() = "Using a regex, pull out only the part I want."

#\d = any digit (0-9)
#+ = one or more occurrences, see all digits if there.
#() = capture this part


#cabin_cat column...  This line extracts the first character from each value in the Cabin column and stores 
#it in a new column called cabin_cat.



#use regular expression --- notes given on drive along with statistics notes

df['cabin_num'] = df['Cabin'].str.extract('(\d+)') # captures numerical part
df['cabin_cat'] = df['Cabin'].str[0] # captures the first letter

df.head()

#value counts reduced alot
df['cabin_cat'].value_counts().plot(kind='bar')





df['Ticket'].unique()
#'A/5 21171',         'PC 17599', 'STON/O2. 3101282','113803'

#apply(...) Applies a function to every value in the Ticket column.
#lambda s: Creates a small anonymous function where s is each ticket value.
#s.split()   Splits the string on spaces.  "A/5 21171".split()
#without giving any argument, Python automatically splits on whitespace:
#if it was hypen "A/5-21171".split("-") use - empty means split by space.
#after splitting python gives a list ['A/5', '21171'][-1]    so -1 here means give me the last part 21171.
#
#the second line..  This converts the extracted strings into numbers. bcz they were extracted as string '21171'
#aur jo number may convert na ho then coerce 'nan' lekhdo wahn.


#same do for cat part
#then use where digit add nan where not digit add that ticket_cat part
## extract the first part of ticket as category
#.str.isdigit()  Checks whether a string contains only digits.
#"349909".isdigit()..... True   
#"A/5".isdigit()..... False
#np.where(condition, value_if_true, value_if_false)
#we used where bcz some ticket has only one part no 2 parts to split. so to remove them if they are digit we used where
# A/5 21171   PC 17599   349909   STON/O2. 3101282 ..... 349909 has only one part no cat part.


# extract the last bit of ticket as number
df['ticket_num'] = df['Ticket'].apply(lambda s: s.split()[-1])
df['ticket_num'] = pd.to_numeric(df['ticket_num'],
                                   errors='coerce',
                                   downcast='integer')

# extract the first part of ticket as category
df['ticket_cat'] = df['Ticket'].apply(lambda s: s.split()[0])
df['ticket_cat'] = np.where(df['ticket_cat'].str.isdigit(), np.nan,
                              df['ticket_cat'])

df.head(20)
df['ticket_cat'].unique()





#inconsistent formats(date format)
#handling date and time
date = pd.read_csv('Data/orders.csv')
time = pd.read_csv('Data/messages.csv')

date.info() 
time.info()

# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])


#1. Extract year

date['date_year'] = date['date'].dt.year   #new column date_year

date.sample(5)




#2. Extract Month

date['date_month_no'] = date['date'].dt.month

date.head()






date['date_month_name'] = date['date'].dt.month_name()

date.head()





#Extract Days

date['date_day'] = date['date'].dt.day

date.head()




#Extract Quarter

date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()




#Extract Semester

date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()



#Extract Time elapsed between dates

import datetime

today = datetime.datetime.today()

today


# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()



#Extract Time part

time['time'] = time['date'].dt.time

time.head()



#Time difference

#today - time['date']


# in seconds

#(today - time['date'])/np.timedelta64(1,'s')


# in minutes

#(today - time['date'])/np.timedelta64(1,'m')

In [ ]:
#########################################################################################

In [ ]:
# identify missing values ways -- 
# 1.visual inspection heat map  
# 2.descriptive statistics % of missing values find  
# 3.missingno library

# ways to handle -- 
# 1. drop 
# 2. drop column 
# 3. substitute mean[prone to outliers so use when normal distribution only]  ---
# median[use if not normal distribution- not prone to outliers] ---- mode --- 
# forward ----  backward fill

# other ways to handle -- 
# KNN imputation[replace with near values average] ---- 
# multivariate impute[considers other columns also then impute]
# deep learning techniques to impute --- Iterative Imputer used.



#numerical -- fill with mean/median or end of distribution or random
#categorical -- fill with mode or 'missing' word write there.


#1. remove values(rows) -- also called CCA(complete case analysis)
#2. simple imputer class(univariate)
#3. KNN imputer(multivariate)
#4. iteratie imputer(multivariate)(MICE algorithm)
#5. missing indicator

In [ ]:
#1. remove values(rows) also called CCA --- dropna
#when to use CCA?
#1. if data MCAR(random missing) not like pattern - like last 20 missing, 1st 20 missing, rather should be missing randomly.
#2. if less than 5% missing. if more missing dont use CCA.

#3. also check after removing missing values the distribution. should remain same not alot change bcz we random removed.
#if before distribution and after distribution changes alot after removing the missing,thats a problem then.
#4. #for categorical variables check before after ratio. 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Data/data_science_job.csv')
df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0.0

In [ ]:
# each column percent missing
df.isnull().mean()*100

df.shape

#columns with less than 5% missing
cols = [var for var in df.columns if df[var].isnull().mean() < 0.05 and df[var].isnull().mean() > 0]
#Go through each column (var). If the condition is true, put var(that column) into the new list."
#gives in % bcz mean used.

#another way to do the same is
cols = []

for var in df.columns:
    if df[var].isnull().mean() < 0.05 and df[var].isnull().mean() > 0:
        cols.append(var)


cols
#it will return column names with less than 5% missing.

df[cols].sample(5) #created new df with only these columns

#lets see how much data will be left after removing missing from above columns..89% something
len(df[cols].dropna()) / len(df)     #total values in new data set "DIVIDE BY" total data in old set.

#after removing missing left new df.
new_df = df[cols].dropna()
df.shape, new_df.shape




#now plot individual columns before after distributions check -- hist plot so to prove that its missing at random if distri remains same.
#plot k uper plot banao

new_df.hist(bins=50, density=True, figsize=(12, 12))
plt.show()

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)

# original data
df['training_hours'].hist(bins=50, ax=ax, density=True, color='red')

# data after cca, the argument alpha makes the color transparent, so we can
# see the overlay of the 2 distributions
new_df['training_hours'].hist(bins=50, ax=ax, color='green', density=True, alpha=0.8)

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)

# original data
df['training_hours'].plot.density(color='red')

# data after cca
new_df['training_hours'].plot.density(color='green')

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)

# original data
df['city_development_index'].hist(bins=50, ax=ax, density=True, color='red')

# data after cca, the argument alpha makes the color transparent, so we can
# see the overlay of the 2 distributions
new_df['city_development_index'].hist(bins=50, ax=ax, color='green', density=True, alpha=0.8)

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)

# original data
df['city_development_index'].plot.density(color='red')

# data after cca
new_df['city_development_index'].plot.density(color='green')

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)

# original data
df['experience'].hist(bins=50, ax=ax, density=True, color='red')

# data after cca, the argument alpha makes the color transparent, so we can
# see the overlay of the 2 distributions
new_df['experience'].hist(bins=50, ax=ax, color='green', density=True, alpha=0.8)

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)

# original data
df['experience'].plot.density(color='red')

# data after cca
new_df['experience'].plot.density(color='green')

In [ ]:
#for categorical variables check before after ratio. 
#ratio ---  column name.value_counts()/len(df)  -- check for all columns before after -- to prove its missing at random
#after CCA the ratio of each category in the column should remain same as it was before.

#first see for enrollment_university column for each of its value counts this ratio.
temp = pd.concat([
            # percentage of observations per category, original data
            df['enrolled_university'].value_counts() / len(df),

            # percentage of observations per category, cca data
            new_df['enrolled_university'].value_counts() / len(new_df)
        ],
        axis=1)    #axis=1 means concat row wise

# add column names
temp.columns = ['original', 'cca']

temp

In [ ]:
temp = pd.concat([
            # percentage of observations per category, original data
            df['education_level'].value_counts() / len(df),

            # percentage of observations per category, cca data
            new_df['education_level'].value_counts() / len(new_df)
        ],
        axis=1)

# add column names
temp.columns = ['original', 'cca']

temp

In [ ]:
############################################################################################

In [ ]:
#Some Descriptive statistics points before we start next imputer

#scales/levels of measurement --- 
#nominal(only english name no order -- male/female -- statsUsed freq,chiSquare),
#ordinal(english name, order/rank -- iagree istronglyAgree -- statsUsed median.mode), 
#interval scale(equal interval plus order plus absolute 0 -- 16C 17C -- statsUsed mean,SD,ANOVA,Reg)
#Ratio Scale(numbers + true 0 -- statsUsed mean,median,mode,SD,geometric mean,harmonic mean) 

#quantitaive data(interval,ratio)
#qualitative data(nominal,ordinal)

#discrete - continous - binary
#time series data - cross sectional data - spartial data
#categorical - continous

In [ ]:
#descriptive statistics
#central tendency -- arithmetic mean, geometric mean, harmonic mean, weighted mean,truncated mean
#median,mode

#measures of dispersion
#Range, IQR, Variance, SD, S.error, coeff of variation CV.

#SD of normal distribution
#data distribution and types of distribution.
#skewness kurtosis

#read descriptive statistics notes to understand from drive

#these things will be used in fixing missing values, outliers problems etc for categorical and numerial data.

In [ ]:
###################################################################################################

In [ ]:
#2. simple imputer class(univariate)

# mean median mode
# substitute mean[prone to outliers so use when normal distribution only]  ---
# median[use if not normal distribution- not prone to outliers] ---- mode --- 
# forward ----  backward fill

#numerical -- fill with mean/median or end of distribution or random
#categorical -- fill with mode or 'missing' word write there.

In [ ]:
#extra covered topics info
# #1. remove values(rows) -- also called CCA(complete case analysis)
#2. Drop column
#2. simple imputer class(univariate)  (mean/median,Arbitory,end of distribution,randomly fill)
#3. KNN imputer(multivariate)
#4. iteratie imputer(multivariate)
#5. missing indicator

In [ ]:
#2. simple imputer class(univariate) 

#univariate way means with help of that same column imputing while multivariate means with help of all columns filling.
#imputing numerical data

#1.mean/median
#2.Arbitory
#3.end of distribution
#4.randomly fill

In [ ]:
#1.mean/median (simple imputer class(univariate)
#if distribution normal -- use mean
#if dist. skewed--- use median

#when to use??
#1. MCAR when data missing completely at random means not pattern wise missing but random missing.
#2. plus if less than 5% missing then use only.


#advantage-- simple to use
#disadvantage-- 1. if >5% missing values then not much reliable.    2. it changes the dist. after applied.
#3. outliers can come which are not outliers but system says it is.
#4. the column which got filled, its relationship with other columns also disturbed(covariance/correlation may change)

#2 ways  1.pandas  2.sklearn

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

df = pd.read_csv('Data/titanic_toy.csv')

df.isnull().mean()

X = df.drop(columns=['Survived'])
y = df['Survived']


#from here onwards see bDatapreproc... skip aBasic notebook....

In [ ]:
#1. remove values(rows) -- also called CCA(complete case analysis)
#2. Drop column
#2. simple imputer class(univariate)  (mean/median,Arbitory,end of distribution,randomly fill)
#3. KNN imputer(multivariate)
#4. iteratie imputer(multivariate)
#5. missing indicator

In [ ]:
#3. KNN imputer(multivariate)

# other ways to handle -- 
# KNN imputation[replace with near values average] ---- 
# multivariate impute[considers other columns also then impute]
# deep learning techniques to impute --- Iterative Imputer used.

In [ ]:
#1. remove values(rows) -- also called CCA(complete case analysis)
#2. Drop column
#2. simple imputer class(univariate)  (mean/median,Arbitory,end of distribution,randomly fill)
#3. KNN imputer(multivariate)
#4. iteratie imputer(multivariate)
#5. missing indicator